"""empty message

Revision ID: 23cf5051a74d
Revises: 68461d7aa241
Create Date: 2023-08-16 01:30:22.307070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23cf5051a74d'
down_revision = '68461d7aa241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.drop_constraint('seller_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.create_unique_constraint('seller_email_key', ['email'])

    # ### end Alembic commands ###
