"""empty message

Revision ID: 54b06ae83c03
Revises: ab338d116f13
Create Date: 2023-08-19 01:36:24.299870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b06ae83c03'
down_revision = 'ab338d116f13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_name', sa.String(length=250), nullable=False))
        batch_op.drop_column('shopName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shopName', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('shop_name')

    # ### end Alembic commands ###
