"""empty message

Revision ID: 68461d7aa241
Revises: b98a80185ca0
Create Date: 2023-08-16 01:00:23.524986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68461d7aa241'
down_revision = 'b98a80185ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('product_id_key', type_='unique')

    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.drop_constraint('seller_id_key', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_id_key', ['id'])

    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.create_unique_constraint('seller_id_key', ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_unique_constraint('product_id_key', ['id'])

    # ### end Alembic commands ###
